
runtime: java11
instance_class: F1
#env: flex
#runtime_config:
#  jdk: openjdk8
#handlers:
#- url: /.*
#  script: this field is required, but ignored
handlers:
- url: /*
  script: this field is required, but ignored

resources:
  cpu: 1
  memory_gb: 16
  disk_size_gb: 15
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50